language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION == 5.3 ]]; then echo 'short_open_tag=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpunit
